server:
  error:
    whitelabel:
      enabled: false
    include-message: always
  port: 8080

spring:

  liquibase:
    enabled: true
    change-log: classpath:liquibase/changelog-master.yaml

  datasource:
    url: jdbc:h2:mem:store_db
    driver-class-name: org.h2.Driver
    username: username
    password: password

  h2:
    console:
      path: /h2-console
      enabled: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
